# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# Not used much since I'm using the native MacOS text replacement. But could reconsider if needed on multiple platforms

matches:
  - trigger: ty
    replace: thank you
    word: true

  - trigger: lmk
    replace: let me know
    word: true
  - trigger: lyk
    replace: let you know
    word: true
